### PR TITLE
Prefs rework

### PR DESCRIPTION
**Pull request by elboulangero**
Hi,

I had some time and inspiration, so I started some code rework on PNMixer.

To me PNMixer code is a little bit of a maze, and I think reworking it is really needed to ease the maintenance. I hope you agree with me.

So I started by reworking a little bit the preferences files, mainly creating get/set accessors to wrap GKeyFile calls, so that prefs.h offer a consistent API. Functions also don't need to expose all the arguments that GKeyFile calls needed. As a result, is much more readable.

So I would like to merge that if nobody's is against. Since it moves / rename a lot of stuff here and there, I just want to be sure that you don't have work in progress.

Following that, I'd like to keep on improving PNMixer code. I'd like to separate the UI related code from the rest, probably having some files like `ui-prefs.c`, `ui-popup.c`. So that in the end UI code is isolated in ui-* files, so we can find our way easily. That would probably means merging the `callbacks.c` file with the new ui-files.

Managing callbacks in a separate file never made sense to me anyway. At the moment, we have two big pieces of code, `create_prefs_window()` and `on_ok_button_clicked()`, that are managed in two different files. But these two functions apply to preferences window, and are kind of counterpart. It would be really nicer to have both in one file. That's what I intend to do.

Furthermore, at the moment we have callbacks that are handled in callbacks.c, but other callbacks are handled in other file (like main.c). So, one more reason to get rid of `callbacks.c`.

So, if nobody's against, I'll merge the current PR, and keep on improving code base in the following days. That mean nobody should work on PNMixer at that time, just to avoid painful merge conflicts afterward.

### CODE REVIEW

**Comment by hasufell** [comment]
https://travis-ci.org/nicklan/pnmixer/jobs/101351399#L318

**Comment by elboulangero** [comment]
My bad, it's fixed now !

**Comment by hasufell** [comment]
Using this branch I always get "Invalid color for volume meter in config file. Reverting to default.". Both on start of pnmixer and preferences saving. I don't even use the volume color meter.

**Comment by elboulangero** [comment]
OK I'll have a look, thanks for checking :)

**Comment by elboulangero** [comment]
Alright, pushed the fix, along with various vol meter color fixes. You should not see the warning message anymore.

**Comment by hasufell** [comment]
That seems to work. Haven't looked a lot at the diff though.

**Comment by elboulangero** [comment]
Cool, let's merge ! The diff is quite huge, but it's mainly moving and renaming code though. Not the kind of thing that's reviewable anyway...

**Pull request merged**
