### PR TITLE
-- Complete rewrite of PNMixer --

### PR DESCRIPTION
**Pull request by elboulangero**

### CODE REVIEW

**Comment by hasufell** [comment]
The 4 jobs that are failing are because the ubuntu images are outdated and don't contain the required gtk3 version. On the other distro images, stuff seems to compile fine. I'll probably update these soon. But shouldn't matter for this PR.

**Comment by elboulangero** [comment]
OK so I merge ?

**Comment by hasufell** [comment]
Maybe wait a few days if people want to comment. I might take a closer look at the weekend if I feel lazy.

**Comment by elboulangero** [comment]
OK

**Comment by hasufell** [comment]
almost a month now... I guess people either don't mind or are too lazy to review  :D 

I'd say we merge! Good job. Been running the thing now and again.

**Comment by elboulangero** [comment]
Merged ! I also run this version for a while now, and it seems to work great.

**Comment by hasufell** [comment]
so this requires a new release then...?

**Comment by elboulangero** [comment]
Yep yep yep ! There's only a few tickets left, then I'm going to contact the Translation Project and try to make the translation with these guys for this release !

**Pull request merged**
