### PR TITLE
Remove trailing whitespaces

### PR DESCRIPTION
**Pull request by jubalh**

### CODE REVIEW

**Comment by hasufell** [comment]
This increases merge conflicts. I'd say at best we merge this after the 0.6 release, not before.

**Comment by jubalh** [comment]
Any guess when 0.6 will get released?

**Comment by elboulangero** [comment]
Yep, we're waiting for russian translation and german translation as well. I didn't have any news from the previous russian translator yet

**Comment by jubalh** [comment]
How to help with translations? I could help with german and maybe with russian. What tools do you use?

**Comment by elboulangero** [comment]
The branch to checkout is `translations-for-0.6`. Then, have a look at the files `po/*.po`. I have updated these files according to the current code, so you just need to edit these files, and fill in what's missing. Nothing else.

About the tools, I personnaly use `emacs` with po mode to edit the po files. Some people use `poedit`. I can't tell you much more, I'm new to all this translation thing.

@mariobl started the german translation some time ago, but there's still some work to be done, mainly translations for the UI files. Have a look at the last commits.

About the russian translation, nothing was done yet. I don't know any russian beings, and the previous translator doesn't reply. I guess I should send a mail to a russian translation team.

**Comment by jubalh** [comment]
@elboulangero I created https://github.com/nicklan/pnmixer/pull/84

**Comment by mariobl** [comment]
Hi Elboulangero,

the updated de.po is attached.

Am 31.07.2015 um 16:57 schrieb elboulangero:
> The branch to checkout is |translations-for-0.6|. Then, have a look at
> the files |po/*.po|. I have updated these files according to the current
> code, so you just need to edit these files, and fill in what's missing.
> Nothing else.
> 
OK, that's the usual way. But translators shouldn't have to bother with
checkout Git modules and/or those branches, see below for an easier way
(probably also easier for you as a developer).

> About the tools, I personnaly use |emacs| with po mode to edit the po
> files. Some people use |poedit|. I can't tell you much more, I'm new to
> all this translation thing.
> 
> @mariobl <https://github.com/mariobl> started the german translation
> some time ago, but there's still some work to be done, mainly
> translations for the UI files. Have a look at the last commits.
> 
> About the russian translation, nothing was done yet. I don't know any
> russian beings, and the previous translator doesn't reply. I guess I
> should send a mail to a russian translation team.
> 
Don't think about how to get translations for a specific language. Just
use one of the common translation projects, like GNU TP, Transifex,
Zanata, whatever. For GNU TP, have a look at the instructions for
maintainers [1]. All you have to do is to generate a pre-release tarball
which contains an up-to-date *.pot file and send the tarball to the TP
Robot. Then the Robot merges the new *.pot template with existing po
files, sends the files to the translation teams, and after a while you
get the updated po files back to a mail address of your choice. That's all.
CC'ing the global TP coordinator.

[1] http://translationproject.org/html/maintainers.html

Best Regards,
Mario

**Comment by elboulangero** [comment]
@mariobl Hi, thanks for the translation, however I didn't get any file attached to the email. Maybe a github stuff or something, can you try to send it again, maybe on my private email only ?

 > Don't think about how to get translations for a specific language. Just use one of the common translation projects, like GNU TP, Transifex, Zanata, whatever. For GNU TP, have a look at the instructions for maintainers [1]. All you have to do is to generate a pre-release tarball which contains an up-to-date *.pot file and send the tarball to the TP Robot. Then the Robot merges the new *.pot template with existing po files, sends the files to the translation teams, and after a while you get the updated po files back to a mail address of your choice. That's all. CC'ing the global TP coordinator.

Yep, OK I will do that, it's just that GNU TP is a little bit impressive when I look at the list of software translated, and I'm afraid it's not the right place for a little piece of soft like PNMixer. But, yeah, I'll try to do it your way, thanks for the advice :)

**Comment by mariobl** [comment]
On 2015-08-04 21:18, Mario Blättermann wrote:
> Don't think about how to get translations for a specific language. Just
> use one of the common translation projects, like GNU TP, Transifex,
> Zanata, whatever.

Yes, that would be much better -- easier for you, and better for
continuity.

> For GNU TP, have a look at the instructions for
> maintainers [1]. All you have to do is to generate a pre-release tarball
> which contains an up-to-date *.pot file and send the tarball to the TP
> Robot.

Well, not a tarball, but just the URL of a tarball.
And not to the robot, but to the coordinators -- me, basically.

> [1] http://translationproject.org/html/maintainers.html

Benno

**Comment by mariobl** [comment]
Hi Elboulangero,

Am 05.08.2015 um 18:57 schrieb elboulangero:
> @mariobl <https://github.com/mariobl> Hi, thanks for the translation,
> however I didn't get any file attached to the email. Maybe a github
> stuff or something, can you try to send it again, maybe on my private
> email only ?

I can't find your private email anywhere. You can fetch the po file from
here:
https://mariobl.fedorapeople.org/Translations/pnmixer.de.po

Best Regards,
Mario

**Comment by elboulangero** [comment]
Hi Mario,
thanks a lot ! Translation commited to PNMixer !

**Comment by elboulangero** [comment]
Trailing whitespaces removed in 76ac55816f10809ec893815824f46948b4b3ada3, thanks.

**Pull request closed without merging**
