### PR TITLE
Fix indenting/coding style

### PR DESCRIPTION
**Pull request by hasufell**
* command: indent --linux-style -psl -cs -l100 ./src/*.[ch]
* fixed 80char linewidth manually

### CODE REVIEW

**Comment by elboulangero** [comment]
> fixed 80char linewidth manually

The linewidth is given with the option `-l100`. If not specified, default is 80, so you can just remove the `-l` option.

I find it useful to use a slightly longer linewidth, especially when using glib, which can have some very long function names. But I'm not so sure, maybe it's better to stick to the usual 80 width, and go longer when it's really needed.

**Comment by elboulangero** [comment]
Maybe we can also setup some git hooks to prevent bad indentation before committing. I aleady saw that on a project.

**Comment by hasufell** [comment]
not sure if github lets you do real hooks, but automated style-check should work somehow

**Comment by elboulangero** [comment]
Wait wait wait !!!

I just stumbled on that: http://astyle.sourceforge.net/
I'll give it a try, I've never been so happy with `indent`. Maybe its output is better.

**Comment by hasufell** [comment]
I'll looked over every file manually, was fine. I can revert however if you want

**Comment by elboulangero** [comment]
No problem, just give me some time to see if this `astyle` tool is better than indent. There are a few things that I don't like too much with indent, for example this bad habit to put spaces after pointers when the type is not a native C type:
`hide_me(GtkWidget * widget, GdkEvent * event, gpointer user_data)`
While a native C type gives:
`main(int argc, char *argv[])`

**Comment by elboulangero** [comment]
Just pushed changes with astyle. Actually I find it smarter than indent. If you OK we can merge that to main, and I'm done with the indenting question for a while :)

**Comment by hasufell** [comment]
I merged it locally with `git merge -X theirs ...`. Looks ok. Should I push?

**Comment by elboulangero** [comment]
Yep. Are we done for the release ?

**Comment by hasufell** [comment]
We'll probably find the first bug after it has been released ;)

**Comment by hasufell** [comment]
I also want to see if I can fix the travis build so it builds gtk2 (with and without libnotify) as well.

**Comment by hasufell** [comment]
`po/pnmixer.pot` is removed on every compile (and recorded as unstaged change), that is a bit annoying

**Comment by elboulangero** [comment]
Yep, it's good to version it, so that translators can get the file easily, no need to type any command. But it disappears on every `make clean`command. I think an easy way is to patch the `Makefile.in.in` (provided by `intltool`) so that it doesn't touch `pnmixer.pot` anymore.

**Comment by hasufell** [comment]
> Yep, it's good to version it, so that translators can get the file easily, no need to type any command. But it disappears on every make cleancommand. I think an easy way is to patch the Makefile.in.in (provided by intltool) so that it doesn't touch pnmixer.pot anymore.

Hm, I don't have a strong opinion there, but `cd po && make pnmixer.pot` is pretty easy, no?

Also: I just ran `make pnmixer.pot && make update-po` which shows that the po-files are already slightly out of date after our indentation fixes.

**Comment by elboulangero** [comment]
> Hm, I don't have a strong opinion there, but cd po && make pnmixer.pot is pretty easy, no?
I agree, but Benno from the TP insisted that translators shouldn't type any command to get the pot file. I don't have any opinion on that either, it depends on their workflow. Another option is: we do not version it, but then when we want the translators to work on PNMixer, we have to create explicitely an archive (with `make dist`), and tells the autotools that the archive must contain the pot file. Maybe it's a better approach.

**Comment by elboulangero** [comment]
Done, I added a dist hook to include the pot file in the dist tarball.

**Comment by elboulangero** [comment]
OK, I fixed the fuzzy translation, updated the pot files. Done with that. These pot files make my git statistics explode :D

**Comment by hasufell** [comment]
travis now builds all permutations ac62dbda8b5864cef6d9b3e6c6c32ebed6827f77

**Pull request merged**
