### PR TITLE
Popup orientation

### PR DESCRIPTION
**Pull request by elboulangero**
Match #116

All in all it was quite easy to implement

### CODE REVIEW

**Comment by elboulangero** [comment]
Tell me what you think, if you're OK we merge that

**Comment by hasufell** [comment]
I'm just wondering how useful this choice actually is. I'm not the minimalist GUI guy but customizing the whole layout shouldn't be priority. Next thing, someone wants a different slider knob ;)

**Comment by elboulangero** [comment]
Well, I don't totally agree with you. Sure it's not priority, but it's not useless either. Depending on one's desktop layout (ie horizontal or vertical panel), or one's personal taste, one may be happy to have this feature. And PNMixer is all about being featurefull, so it makes sense.

Customizing the layout is quite simple, since the popup window is really a simple thing (see 615068).
The whole changeset is not big and doesn't add anything tricky.

And to finish, I must say that I've been thinking about that from the very beginning of the Gtk3 port, since I much preferred the horizontal layout. So it's true, this feature is for me, but I decided to implement it only after reading someone saying that he preferred the horizontal layout too, so it's not totally selfish. To me it makes PNMixer a little bit better.

**Comment by hasufell** [comment]
Sure, if you like to spend time on it.

**Comment by elboulangero** [comment]
Reworked and done in #118

**Pull request closed without merging**
