### PR TITLE
Popup orientation 2

### PR DESCRIPTION
**Pull request by elboulangero**
Better implementation.

In a few words (read commit messages for more details):

- in a first time, split popup ui file, since it contains two different popup completely unrelated: menu popup and volume popup.
- now that volume popup has its own files (which is very short and simple), I just duplicate it and edit the layout. So there's one ui file for horizontal layout, one for vertical layout.

Compared to the former PR  (#117), this implementation has the advantage to be more straight forward. It doesn't add little tricky and weird code, it's gonna be easier to read and understand how the two layouts are implemented. So, better in term of maintenance.

Also, it works with Gtk2 too.

### CODE REVIEW

**Comment by elboulangero** [comment]
I improved the two layouts feature, now the implementation looks better, less tricky. I'll merge that if nobody speaks against it :)

**Comment by hasufell** [comment]
where do the merge conflicts come from?

**Comment by elboulangero** [comment]
I've been touching the same files on master, just to make the merge a liitle bit more challenging ;)

**Comment by elboulangero** [comment]
Merged !

**Pull request merged**
