### PR TITLE
pref-dialog: add style-class frame

### PR DESCRIPTION
**Pull request by raveit65**
The GtkNotebook can now address with
notebook.frame {}
by a gtk+-3 theme

A lot of themes are using notebook.frame {} for styling a notebook inside a dialog window.
Example BlueSubmarine from MATE desktop.
w/o this PR:
pnmixer-bad

with the PR:
pnmixer-good

This doesn't have an effect for themes wo doesn't use the frame style-class here, eg. Adwaita.

Btw. i updated pnmixer in fedora to latest version and switched to gtk+-3.
Pnmixer will become the default mixer-applet for the MATE desktop for fedora 28 ;-)
I am using pavucontrol as mixer for fedora.

### CODE REVIEW

**Comment by raveit65** [comment]
You should really check your travis CI config,
Pnmixer builds fine at fedora build server with this patch ;-)
https://kojipkgs.fedoraproject.org//packages/pnmixer/0.7.2/1.fc28/data/logs/x86_64/build.log

**Comment by hasufell** [comment]
Did you add that thing with the glade editor or manually?

**Comment by raveit65** [comment]
with
[rave@mother ~]$ rpm -qa glade*
glade-3.20.0-3.fc26.x86_64

**Comment by hasufell** [comment]
Good, because we also use glade and try to avoid manual changes, because next time someone opens the files in glade, it will save them in a different order/format.

**Comment by hasufell** [comment]
@elboulangero seems to work for me, do you still have the ability to test pnmixer?

**Comment by hasufell** [comment]
Why did you close this PR?

**Comment by elboulangero** [comment]
> Btw. i updated pnmixer in fedora to latest version and switched to gtk+-3.

Great to hear that, thanks !

> Pnmixer will become the default mixer-applet for the MATE desktop for fedora 28 ;-)

Hmm, well I can't say for sure, but I would assume fully featured desktops like MATE use PulseAudio. And this is an issue. PNMixer is an ALSA only mixer, and is known to misbehave when PulseAudio is around.

**Comment by elboulangero** [comment]
@raveit65

> A lot of themes are using notebook.frame {} for styling a notebook inside a dialog window.

Any example of 'lot of themes' ?

> Example BlueSubmarine from MATE desktop.

I see that you're a developer of this theme. So should I understand that *you personally* use `notebook.frame` to theme gtk notebooks ?

The commit you propose is a bit weird. A gtk application developer is not supposed to add some random css classes to his widgets *just in case* some theme developer, somewhere, decided to implement this class. I don't think gtk css is supposed to be used this way.

Of course you're free to prove me wrong by providing links on this topic.

**Pull request closed without merging**
