### PR TITLE
Proposal: switch to CMake

### PR DESCRIPTION
**Pull request by hasufell**
Don't merge, this is just for discussion, testing etc.

See #157

### CODE REVIEW

**Comment by hasufell** [comment]
Performance test:

__CMake__
```
jule@localhost ~/git/pnmixer $ time sh -c 'mkdir build && cd build && cmake .. && make -j8 && make DESTDIR="/home/jule/git/pnmixer/install" install && cd ..'
...
real	0m1,464s
user	0m3,499s
sys	0m0,605s
```

__Autotools__
```
jule@localhost ~/git/pnmixer2 $ time sh -c './autogen.sh && make -j8 && make DESTDIR="/home/jule/git/pnmixer2/install" install'
...
real	0m6,071s
user	0m6,365s
sys	0m0,727s
```

**Comment by elboulangero** [comment]
I'm not familiar with cmake, I though it was more suited for C++. This being said, if you like it, I'm OK to go for it. I just would like to tag a 0.7.1 version before that.

**Comment by hasufell** [comment]
> I just would like to tag a 0.7.1 version before that.

Hm, wouldn't 0.7.1 be the perfect candidate for it?

**Comment by elboulangero** [comment]
Well, no, I'd like to package the version 0.7.1 for Debian, and basically addressing all the details pointed by some debian packagers in the 0.7 version. Just sticking to these points is less headaches for me. Introducing a new build system will create new headaches I'm sure, and I'd like to keep it for a next 0.7.2 version ;)

**Comment by hasufell** [comment]
It's less headache than autotools actually

**Comment by elboulangero** [comment]
Just talking about the packaging part, I want it to be quick and simple, and the best way for that is to stick to autotools instead of having to learn about cmake.

**Comment by hasufell** [comment]
Well. Pretty much your choice... but you're not required to _learn_ cmake. You just have to know how to _use_ it.

After you've done `mkdir build && cd build && cmake ..` you're left with autotools like makefiles that also respect DESTDIR. Options are explained in the readme and passed as part of the cmake call e.g. `cmake -DWITH_GTK3=ON`. Prefix, binary dir etc. are passed similarly e.g. `cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_DATADIR=/usr/share -DCMAKE_INSTALL_BINDIR=/usr/host/bin`

Translations are built by default. Nothing special to do there

**Comment by elboulangero** [comment]
Ok well if you're really comfortable with that, let's go for it, we include in 0.7.1. But I expect support if ever some Debian guy review the package and asks weird questions !!!

**Comment by hasufell** [comment]
I think it's pullable now. Maybe you want to give it a quick test?

**Pull request merged**
