### PR TITLE
Continue with german translation

### PR DESCRIPTION
**Pull request by jubalh**
Added new things and updates some which in my opinion where not right.

### CODE REVIEW

**Comment by jubalh** [comment]
First time doing a translation with .po files. Hope it is alright.

Not sure about https://github.com/jubalh/pnmixer/commit/9b8dad47463d398feee0ac70cdf478a17c913216#diff-5b78fe3b8a66eafe677903fefeaeb0ccL328 since the original spans across mutliple lines or something?

Looking forward for review

**Comment by jubalh** [comment]
@elboulangero What do you think?

**Comment by elboulangero** [comment]
Hi @jubalh, thanks for the commit. To be honest I can't review anything, I don't speak german at all, and I'm new at translation also :)

Maybe you noticed, @mariobl sent an updated PO file with the german translation. I will merge his work, since I asked him first and he started the translation first. I'm sorry I should have been more explicit, I realize now that it wasn't very clear that he started german translation already. And I didn't know because I had no news from him, but I should have been more patient and wait a little bit. I hope there's no offense.

Anyway, after that you can always discuss details and things, no problem, but I will be of no help since I'm not a german speaker.

**Comment by elboulangero** [comment]
> Not sure about jubalh@9b8dad4#diff-5b78fe3b8a66eafe677903fefeaeb0ccL328 since the original spans across mutliple lines or something?
No idea, I saw that the french translation removed the newline, the italian kept it...

**Comment by jubalh** [comment]
So just merge it :)

**Comment by jubalh** [comment]
6 days ago in, https://github.com/nicklan/pnmixer/pull/82 I asked when 
you will release the new version. You told me you are waiting for 
russian and german translation. I then said I can help with that. I then 
send in a PR just some hours afterwards. And days later you received the 
other.

Strange.

**Comment by hasufell** [comment]
What's the status here? I lost track between the different guys working on this.

**Comment by elboulangero** [comment]
Yep, so we have French, Italian and German translated. Russian still missing.

Another missing thing, the `.desktop` file is not translated automatically at the moment. I'm working my way through the autotools black magic to fix that. When I'm done, I update the PO files, so there will be two new strings to translate (coming from 50a5bcae), plus the `.desktop` file for Italian and Russian.

I will post to a translation project, which is the way I should have done from the beginning according to Mario and Benno. This discussion happened on #82 somehow. It's a bit difficult to follow, Mario is in fact two persons !

Then I hope I will have some feedback quickly.

**Comment by elboulangero** [comment]
@hasufell Can we remove the branches marked as "Staled" ? They're marked as merged, or are not relevant anymore.

**Comment by hasufell** [comment]
sure, since they are not continuous branches

**Comment by elboulangero** [comment]
Cool, I like when my `git remote show origin` output is as empty as possible :)

**Pull request closed without merging**
